---
# tasks file for roles/docker
- name: Install required system packages
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add the user to the docker group
  become: yes
  user:
    name: "ubuntu"
    groups: docker
    append: yes

- name: Restart Docker to apply group changes
  become: yes
  service:
    name: docker
    state: restarted

- name: Copy application to remote
  copy:
    src: ./app
    dest: /home/ubuntu
    owner: ubuntu
    group: ubuntu

- name: build container image
  docker_image:
    name: app:v1.0
    build:
      dockerfile: /home/ubuntu/app/Dockerfile
      path: /home/ubuntu/app
      nocache: true
    state: present
    source: build

- name: Create default containers
  community.docker.docker_container:
    name: "app-devops"
    image: "app:v1.0"
    state: started
    network_mode: "host"
